### ISSUE TITLE
use parent classname as child prefix in scss / 在scss中使用父类前缀

### ISSUE THREAD

**Issue by JiangWeixian** [JiangWeixian/cheatsheets#134]
```css
.report {
  &_title {
    color: white
  }
}
```

会编译为`report_title`
