### ISSUE TITLE
define object on github action / 定义对象变量

### ISSUE THREAD

**Issue by JiangWeixian** [JiangWeixian/cheatsheets#163]
```yaml
jobs:
	  build:
	      runs-on: ${{ matrix.os }}
	      needs: analyze-tags
	      strategy:
	        matrix:
	          os: [ubuntu-latest, macos-latest]
	      name: ${{ matrix.os }}
	      steps:
	        - name: Set arch var
	          id: vars
	          run: |
	            echo ::set-output name=arch::\
	            $(echo '{ "ubuntu-latest": "x86_64-unknown-linux-musl", "macos-latest": "x86_64-apple-darwin" }' | jq -r 'to_entries[] | select(.key=="${{ matrix.os }}") | .value')
```

这样就定义了一个对象，且通过运行的 OS 作为 KEY，获取对应的 VALUE。在任意地方可以通过`${{ steps.vars.outputs.arch }}`获取到设置 VALUE。如

```yaml
- name: Prepare builds Dir
  run: mkdir builds && mkdir builds/jscpdrs-cli-${{ steps.vars.outputs.arch }}
```
