### ISSUE TITLE
control github action step run or not / 控制Github Action步骤运行与否

### ISSUE THREAD

**Issue by JiangWeixian** [JiangWeixian/cheatsheets#164]
```yaml
- name: Release Homebrew
  uses: softprops/action-gh-release@v1
  if: ${{ steps.vars.outputs.arch == 'x86_64-apple-darwin' }}
  with:
    files: builds/jscpdrs.tar.gz
    tag_name: ${{ needs.analyze-tags.outputs.previous-tag }}
```

如果`if`不成立，就不会运行这个`Release Homebrew`
