### ISSUE TITLE
Release npm packages on Github workflows.

### ISSUE THREAD

**Issue by JiangWeixian** [JiangWeixian/cheatsheets#260]
> `permissions` is required
>  Check <https://github.com/{repo}/settings/actions> Workflow permissions with `Allow github actions create and approve pull request` & `Read & Write permissons`.

```yaml
name: Release
on:
  push:
    branches:
      - main
      - master
      - 'releases/*'
env:
  CI: true
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
      issues: read
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: install pnpm
        run: npm i pnpm@7.23.0 -g
      - name: install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: create and publish versions
        uses: changesets/action@master
        with:
          version: pnpm ci:version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
