### ISSUE TITLE
hide scollbar

### ISSUE THREAD

**Issue by JiangWeixian** [JiangWeixian/cheatsheets#94]
```css
::-webkit-scrollbar {
  width: 0px;  /* Remove scrollbar space */
  background: transparent;  /* Optional: just make scrollbar invisible */
}
::-webkit-scrollbar-thumb {
  background: transparent;
}
```
